/**
 * scenarioService.js
 *
 * Orchestrates scenario speaking practice + IELTS speaking exam.
 *
 * IELTS sessions use an EXPLICIT STATE MACHINE:
 *  - State is persisted in DB (session_meta JSONB column)
 *  - Each submitTurn call reads the current state, processes the turn,
 *    then EXPLICITLY advances to the next state
 *  - Turn count is NOT used to derive state — state drives everything
 *  - State transitions are logged for auditability
 */

const { createAiProvider } = require("../providers/ai/aiProvider");
const scenarioRepository = require("../repositories/scenarioRepository");
const { analyzeSpeechFlow, aggregateSpeechFlow } = require("./speechAnalyzer");
const { updateStreak } = require("./streakService");
const { awardXp } = require("./xpService");
const {
  pickPersona,
  computeGreeting,
  buildOpeningMessage,
  normalizeTimezone,
} = require("../domain/ielts/examinerPersona");

// ---------------------------------------------------------------------------
// XP rewards
// ---------------------------------------------------------------------------
// Flat rewards per session completion. Scaled slightly for IELTS exam
// (full 3-part simulation) vs regular scenario (single-topic conversation).
const XP_REWARD_SCENARIO = 15;
const XP_REWARD_IELTS    = 25;

const ai = createAiProvider();

// ---------------------------------------------------------------------------
// IELTS Constants
// ---------------------------------------------------------------------------

const IELTS_PART1_QUESTIONS_PER_BLOCK = 3;
const IELTS_PART1_TOPIC_BLOCKS = 2;
const IELTS_PART1_TOTAL_QUESTIONS = IELTS_PART1_QUESTIONS_PER_BLOCK * IELTS_PART1_TOPIC_BLOCKS; // 6
const IELTS_PART3_QUESTIONS = 4;

// Part 3 discussion tiers — each question escalates
const PART3_TIERS = ["concrete", "comparative", "analytical", "evaluative"];

// ---------------------------------------------------------------------------
// HARDCODED TRANSITIONS — NEVER generated by LLM
// These strings are the ONLY valid transition outputs. No modification allowed.
// ---------------------------------------------------------------------------

const FIXED_TRANSITIONS = {
  part1: "Now let's start Part 1.",
  part2: "Okay, let's move on to Part 2.",
  part3: "Okay, let's move on to Part 3.",
  closing: "That is the end of the speaking test.",
  prepStart: "Your preparation time is over. Please begin speaking now.",
};

// V2: More natural, professional examiner transitions
const FIXED_TRANSITIONS_V2 = {
  part1: "Let's begin with Part 1. I'm going to ask you some questions about yourself.",
  part2: "Now I'm going to give you a topic, and I'd like you to talk about it for one to two minutes. Before you talk, you'll have one minute to think about what you're going to say.",
  part3: "We've been talking about your topic, and I'd like to discuss some more general questions related to it.",
  closing: "Thank you very much. That is the end of the speaking test. Thank you for your time.",
  prepStart: "All right, your preparation time is over. Please begin speaking now.",
};

// ---------------------------------------------------------------------------
// BANNED PHRASES — stripped from any LLM output
// ---------------------------------------------------------------------------

const BANNED_PATTERNS = [
  /\bthat(?:'s| is) (?:very |really |quite )?interesting\b/i,
  /\bgood (?:answer|point|response)\b/i,
  /\bwell done\b/i,
  /\bgreat\b/i,
  /\bnice\b/i,
  /\bwonderful\b/i,
  /\bexcellent\b/i,
  /\bfantastic\b/i,
  /\bthank you for (?:your |that |sharing)\b/i,
  /\bthank you\.\s*/i,
  /\bthanks\.\s*/i,
  /\bI see\.\s*/i,
  /\bright\.\s*/i,
  /\balright\.\s*/i,
  /\bi appreciate\b/i,
  /\blet me ask you\b/i,
  /\bi'd like (?:to |you to )\b/i,
  /\blet's talk about\b/i,
  /\bcan you tell me\b/i,
  /\bcould you tell me\b/i,
  /\bI'd like to ask you\b/i,
];

// Max words for a single examiner question
const MAX_QUESTION_WORDS = 15;

// ---------------------------------------------------------------------------
// Output Validation Layer — enforces examiner contract
// ---------------------------------------------------------------------------

/**
 * Sanitize LLM output to enforce examiner rules:
 * - Strip banned phrases
 * - Enforce single sentence
 * - Cap word count
 * - Remove reaction prefixes
 */
function sanitizeExaminerOutput(text) {
  let cleaned = text.trim();

  // Strip any reaction/acknowledgment prefix
  cleaned = cleaned.replace(/^(?:Thank you\.|Thanks\.|Okay\.|Right\.|Alright\.|I see\.|Okay, thank you\.)\s*/i, "");

  // Strip banned patterns
  for (const pattern of BANNED_PATTERNS) {
    cleaned = cleaned.replace(pattern, "");
  }

  // Clean up double spaces and leading/trailing whitespace
  cleaned = cleaned.replace(/\s{2,}/g, " ").trim();

  // Enforce single sentence: take only the first sentence that ends with ? or .
  const sentenceMatch = cleaned.match(/^[^.?!]+[.?!]/);
  if (sentenceMatch) {
    cleaned = sentenceMatch[0].trim();
  }

  // Cap word count — if too long, truncate to last complete phrase
  const words = cleaned.split(/\s+/);
  if (words.length > MAX_QUESTION_WORDS) {
    cleaned = words.slice(0, MAX_QUESTION_WORDS).join(" ");
    // Ensure it ends with a question mark if it looks like a question
    if (!cleaned.endsWith("?") && !cleaned.endsWith(".")) {
      cleaned += "?";
    }
  }

  // Final safety: examiner output must be a question
  if (cleaned && !cleaned.endsWith("?")) {
    // If it ends with a period, replace with question mark
    if (cleaned.endsWith(".")) {
      cleaned = cleaned.slice(0, -1) + "?";
    } else {
      cleaned += "?";
    }
  }

  return cleaned || "What is your opinion on that?";
}

// ---------------------------------------------------------------------------
// IELTS Part 1 Topic Sets — diverse personal/familiar topics
// Each set has a theme and specific question prompts for the AI to use.
// ---------------------------------------------------------------------------

const IELTS_PART1_TOPIC_SETS = [
  {
    theme: "Home & Accommodation",
    questions: [
      "Can you describe the place where you live?",
      "What do you like most about your home?",
      "Is there anything you would like to change about your home?",
      "Do you plan to live there for a long time?",
    ],
  },
  {
    theme: "Work & Studies",
    questions: [
      "Do you work or are you a student?",
      "What do you enjoy most about your work or studies?",
      "Would you like to change your job or field of study in the future?",
      "What did you want to be when you were younger?",
    ],
  },
  {
    theme: "Hometown & Neighbourhood",
    questions: [
      "Where is your hometown?",
      "What is the best thing about living there?",
      "Has your hometown changed much in recent years?",
      "Would you recommend your hometown to visitors?",
    ],
  },
  {
    theme: "Daily Routine & Leisure",
    questions: [
      "What does a typical day look like for you?",
      "Do you prefer mornings or evenings?",
      "How do you usually relax after a busy day?",
      "Has your daily routine changed recently?",
    ],
  },
  {
    theme: "Food & Cooking",
    questions: [
      "What kind of food do you enjoy eating?",
      "Do you prefer eating at home or in restaurants?",
      "Have you ever tried cooking a dish from another country?",
      "Is there a food you disliked as a child but enjoy now?",
    ],
  },
  {
    theme: "Travel & Transport",
    questions: [
      "How do you usually travel to work or school?",
      "Do you enjoy travelling to new places?",
      "What was the last trip you took?",
      "Do you prefer travelling alone or with others?",
    ],
  },
  {
    theme: "Technology & Internet",
    questions: [
      "How often do you use the internet?",
      "What do you mainly use your phone for?",
      "Do you think people spend too much time on technology?",
      "Is there a piece of technology you could not live without?",
    ],
  },
  {
    theme: "Friends & Social Life",
    questions: [
      "Do you prefer spending time with a few close friends or a large group?",
      "How do you usually keep in touch with friends?",
      "Have your friendships changed since you were younger?",
      "What qualities do you value most in a friend?",
    ],
  },
];

// ---------------------------------------------------------------------------
// IELTS Part 2 Cue Cards — expanded with Part 3 theme link
// ---------------------------------------------------------------------------

const IELTS_CUE_CARDS = [
  { topic: "Describe a place you would like to visit", prompts: ["Where the place is", "How you heard about it", "What you would do there", "Why you would like to visit it"], part3Theme: "tourism and travel" },
  { topic: "Describe a person who has inspired you", prompts: ["Who this person is", "How you know them", "What they have done that inspired you", "Why they have been important to you"], part3Theme: "role models and influence" },
  { topic: "Describe a skill you would like to learn", prompts: ["What the skill is", "Why you want to learn it", "How you would learn it", "How useful this skill would be for you"], part3Theme: "learning and education" },
  { topic: "Describe a memorable journey you have made", prompts: ["Where you went", "Who you went with", "What happened during the journey", "Why this journey was memorable"], part3Theme: "travel experiences and transportation" },
  { topic: "Describe a book or film that made you think", prompts: ["What it was about", "When you read or watched it", "What ideas it presented", "Why it made an impression on you"], part3Theme: "media, culture, and storytelling" },
  { topic: "Describe a time you helped someone", prompts: ["Who you helped", "Why they needed help", "How you helped them", "How you felt afterwards"], part3Theme: "helping others and community" },
  { topic: "Describe a tradition in your country that you enjoy", prompts: ["What the tradition is", "When it takes place", "How people celebrate or practise it", "Why it is important to you personally"], part3Theme: "culture and traditions" },
  { topic: "Describe a piece of technology that has changed your daily life", prompts: ["What the technology is", "When you started using it", "How you use it in your daily life", "How your life was different before you had it"], part3Theme: "technology and modern life" },
  { topic: "Describe an achievement you are proud of", prompts: ["What you achieved", "When it happened", "How you achieved it", "Why you feel proud of it"], part3Theme: "success, ambition, and motivation" },
  { topic: "Describe a time when you had to make a difficult decision", prompts: ["What the decision was", "Why it was difficult", "What you decided to do", "How you felt about the outcome"], part3Theme: "decision-making and responsibility" },
  { topic: "Describe a public place you enjoy visiting", prompts: ["What the place is", "Where it is located", "What you do there", "Why you enjoy going there"], part3Theme: "public spaces and urban planning" },
  { topic: "Describe a hobby or activity you enjoy doing in your free time", prompts: ["What the activity is", "How often you do it", "Who you do it with", "Why you find it enjoyable"], part3Theme: "leisure, hobbies, and work-life balance" },
];

// ---------------------------------------------------------------------------
// V2: Cue card → preferred Part 1 topic alignment
// Maps cue card index → preferred Part 1 topic set indices (0-based into IELTS_PART1_TOPIC_SETS)
// Used on retry to keep Part 1 thematically consistent with Part 2.
// Each entry lists 2 preferred topic sets that relate to the cue card theme.
// ---------------------------------------------------------------------------

const CUE_CARD_TOPIC_ALIGNMENT = [
  /* 0: place to visit       */ [5, 2], // Travel & Transport, Hometown
  /* 1: inspiring person      */ [7, 1], // Friends & Social, Work & Studies
  /* 2: skill to learn        */ [1, 3], // Work & Studies, Daily Routine
  /* 3: memorable journey     */ [5, 2], // Travel & Transport, Hometown
  /* 4: book/film that made you think */ [3, 6], // Daily Routine & Leisure, Technology
  /* 5: time you helped someone */ [7, 1], // Friends & Social, Work & Studies
  /* 6: tradition you enjoy   */ [4, 2], // Food & Cooking, Hometown
  /* 7: technology changed life */ [6, 3], // Technology, Daily Routine
  /* 8: achievement proud of  */ [1, 3], // Work & Studies, Daily Routine
  /* 9: difficult decision    */ [1, 7], // Work & Studies, Friends & Social
  /* 10: public place you enjoy */ [2, 3], // Hometown, Daily Routine
  /* 11: hobby/free time      */ [3, 7], // Daily Routine, Friends & Social
];

// ---------------------------------------------------------------------------
// IELTS State Machine — Explicit Transitions
// ---------------------------------------------------------------------------

/**
 * State shape (persisted in session_meta JSONB):
 * {
 *   part: 1 | 2 | 3,
 *   phase: "question" | "transition_to_part2" | "cue_card" | "long_turn" |
 *          "follow_up" | "transition_to_part3" | "question_p3" | "complete",
 *   questionIndex: number,         // 0-based within current part
 *   cueCardIndex: number,          // index into IELTS_CUE_CARDS
 *   transitionHistory: string[],   // audit trail of state transitions
 * }
 */

/**
 * Create the initial IELTS state for a new session.
 */
function createInitialIeltsState(cueCardIndex, useAlignedTopics = false) {
  let topicSetIndices;

  if (useAlignedTopics && CUE_CARD_TOPIC_ALIGNMENT[cueCardIndex]) {
    // V2: Use thematically aligned Part 1 topics for retry consistency
    topicSetIndices = CUE_CARD_TOPIC_ALIGNMENT[cueCardIndex];
  } else {
    // Default: random 2 topic sets
    const allIndices = Array.from({ length: IELTS_PART1_TOPIC_SETS.length }, (_, i) => i);
    const shuffled = allIndices.sort(() => Math.random() - 0.5);
    topicSetIndices = [shuffled[0], shuffled[1]];
  }

  return {
    part: 1,
    phase: "opening",         // Examiner asks name only
    questionIndex: 0,
    cueCardIndex,

    // ── Part 1 Topic Engine ──
    topicSetIndices,
    currentTopicBlock: 0,

    // ── Part 3 Discussion Ladder ──
    part3Tier: 0,
    part3PrevWordCount: 0,

    // ── Quality tracking ──
    userWordCounts: [],
    userResponses: [],
    userResponseCount: 0,
    transitionHistory: ["init → part1:opening:0"],
  };
}

/**
 * EXPLICIT state transition — given the current state + the fact that the user
 * just submitted a turn, compute the NEXT state.
 *
 * This is NOT based on turn count. It reads the current state and advances it.
 * Each transition is logged in transitionHistory for auditability.
 */
function advanceIeltsState(currentState) {
  const next = { ...currentState, transitionHistory: [...currentState.transitionHistory] };
  const from = `part${next.part}:${next.phase}:${next.questionIndex}`;

  // ── Part 1: opening → part1_transition ──
  if (next.part === 1 && next.phase === "opening") {
    next.phase = "part1_transition";
    next.transitionHistory.push(`${from} → part1:part1_transition:0`);
    return next;
  }

  // ── Part 1: part1_transition → question:0 ──
  if (next.part === 1 && next.phase === "part1_transition") {
    next.phase = "question";
    next.questionIndex = 0;
    next.transitionHistory.push(`${from} → part1:question:0`);
    return next;
  }

  // ── Part 1: question → question → ... → transition_to_part2 ──
  if (next.part === 1 && next.phase === "question") {
    if (next.questionIndex + 1 >= IELTS_PART1_TOTAL_QUESTIONS) {
      // All Part 1 questions asked → transition to Part 2
      next.part = 2;
      next.phase = "transition_to_part2";
      next.questionIndex = 0;
    } else {
      next.questionIndex += 1;
      // Update topic block when crossing boundary
      const newBlock = Math.floor(next.questionIndex / IELTS_PART1_QUESTIONS_PER_BLOCK);
      if (newBlock !== next.currentTopicBlock) {
        next.currentTopicBlock = newBlock;
      }
    }
    next.transitionHistory.push(`${from} → part${next.part}:${next.phase}:${next.questionIndex}`);
    return next;
  }

  // ── Part 2: transition_to_part2 → cue_card (user preps) ──
  if (next.part === 2 && next.phase === "transition_to_part2") {
    next.phase = "cue_card";
    next.transitionHistory.push(`${from} → part2:cue_card:0`);
    return next;
  }

  // ── Part 2: cue_card → long_turn (user speaks for 2 min) ──
  if (next.part === 2 && next.phase === "cue_card") {
    next.phase = "long_turn";
    next.transitionHistory.push(`${from} → part2:long_turn:0`);
    return next;
  }

  // ── Part 2: long_turn → transition_to_part3 (skip follow-up for clean IELTS flow) ──
  if (next.part === 2 && next.phase === "long_turn") {
    next.part = 3;
    next.phase = "transition_to_part3";
    next.questionIndex = 0;
    next.transitionHistory.push(`${from} → part3:transition_to_part3:0`);
    return next;
  }

  // ── Part 2: follow_up → transition_to_part3 (legacy — kept for backward compat) ──
  if (next.part === 2 && next.phase === "follow_up") {
    next.part = 3;
    next.phase = "transition_to_part3";
    next.questionIndex = 0;
    next.transitionHistory.push(`${from} → part3:transition_to_part3:0`);
    return next;
  }

  // ── Part 3: transition_to_part3 → question_p3 ──
  if (next.part === 3 && next.phase === "transition_to_part3") {
    next.phase = "question_p3";
    next.part3Tier = 0; // Start at concrete tier
    next.transitionHistory.push(`${from} → part3:question_p3:0`);
    return next;
  }

  // ── Part 3: question_p3 → question_p3 → ... → complete ──
  if (next.part === 3 && next.phase === "question_p3") {
    if (next.questionIndex + 1 >= IELTS_PART3_QUESTIONS) {
      next.phase = "complete";
    } else {
      next.questionIndex += 1;
      // ── Discussion Ladder: advance tier ──
      const baseTier = next.questionIndex; // 0→0, 1→1, 2→2, 3→3
      // De-escalation: if previous answer was very short (<15 words), drop one tier
      if (next.part3PrevWordCount > 0 && next.part3PrevWordCount < 15 && baseTier > 0) {
        next.part3Tier = Math.max(0, baseTier - 1);
      } else {
        next.part3Tier = Math.min(baseTier, PART3_TIERS.length - 1);
      }
    }
    next.transitionHistory.push(`${from} → part${next.part}:${next.phase}:${next.questionIndex}`);
    return next;
  }

  // Already complete — no transition
  return next;
}

/**
 * Multi-signal response quality analysis for adaptive difficulty.
 *
 * Signals:
 * - avgWordCount: average words per response
 * - vocabComplexity: ratio of words > 6 chars (proxy for advanced vocabulary)
 * - sentenceComplexity: avg commas + conjunctions per response (proxy for compound/complex sentences)
 *
 * Returns: { level: "strong"|"moderate"|"limited", avgWords, vocabRatio, complexityAvg }
 */
function analyzeResponseQuality(state) {
  const counts = state.userWordCounts || [];
  const responses = state.userResponses || [];

  if (counts.length === 0) {
    return { level: "unknown", avgWords: 0, vocabRatio: 0, complexityAvg: 0 };
  }

  const avgWords = counts.reduce((a, b) => a + b, 0) / counts.length;

  // Vocabulary complexity: ratio of "long" words (>6 chars) across all responses
  let totalWords = 0;
  let longWords = 0;
  let totalComplexitySignals = 0;

  for (const text of responses) {
    const words = text.trim().split(/\s+/).filter(Boolean);
    totalWords += words.length;
    longWords += words.filter(w => w.replace(/[^a-zA-Z]/g, "").length > 6).length;
    // Sentence complexity signals: commas, semicolons, conjunctions
    const commas = (text.match(/,/g) || []).length;
    const conjunctions = (text.match(/\b(because|although|however|moreover|furthermore|nevertheless|whereas|therefore|consequently)\b/gi) || []).length;
    totalComplexitySignals += commas + conjunctions * 2;
  }

  const vocabRatio = totalWords > 0 ? longWords / totalWords : 0;
  const complexityAvg = responses.length > 0 ? totalComplexitySignals / responses.length : 0;

  // Composite scoring
  let score = 0;
  if (avgWords >= 40) score += 3;
  else if (avgWords >= 25) score += 2;
  else if (avgWords >= 12) score += 1;

  if (vocabRatio >= 0.20) score += 2;
  else if (vocabRatio >= 0.10) score += 1;

  if (complexityAvg >= 2.0) score += 2;
  else if (complexityAvg >= 1.0) score += 1;

  const level = score >= 5 ? "strong" : score >= 3 ? "moderate" : "limited";

  return { level, avgWords, vocabRatio, complexityAvg };
}

// ---------------------------------------------------------------------------
// Examiner Brain — Helper functions
// ---------------------------------------------------------------------------

/**
 * Get the current topic set for the active Part 1 block.
 */
function getCurrentTopicSet(state) {
  const blockIdx = state.currentTopicBlock || 0;
  const indices = state.topicSetIndices || [0, 1];
  const topicIdx = indices[Math.min(blockIdx, indices.length - 1)];
  return IELTS_PART1_TOPIC_SETS[topicIdx % IELTS_PART1_TOPIC_SETS.length];
}

/**
 * Get the question hint for the current position within the current topic block.
 */
function getQuestionHint(state) {
  const topicSet = getCurrentTopicSet(state);
  const posInBlock = state.questionIndex % IELTS_PART1_QUESTIONS_PER_BLOCK;
  return topicSet.questions[Math.min(posInBlock, topicSet.questions.length - 1)];
}

/**
 * Check if we're at the start of a new topic block (topic transition needed).
 */
function isTopicTransition(state) {
  return state.questionIndex > 0 && state.questionIndex % IELTS_PART1_QUESTIONS_PER_BLOCK === 0;
}

/**
 * CONTROLLED EXAMINER PROMPT — minimal, no personality, no reactions.
 *
 * The examiner is NOT conversational. It generates exactly ONE utterance:
 * either a single question or nothing (transitions are hardcoded).
 *
 * Output contract:
 * - ONE sentence
 * - MAX 12 words (for questions)
 * - ZERO reactions to user answers
 * - ZERO praise, acknowledgment, or filler
 */
function buildIeltsSystemPrompt(state) {
  const cueCard = IELTS_CUE_CARDS[state.cueCardIndex % IELTS_CUE_CARDS.length];

  const base = `You generate IELTS Speaking examiner questions. Output ONLY the question — nothing else.

ABSOLUTE RULES:
- Output exactly ONE question. No commentary, no filler.
- Maximum 12 words.
- NEVER react to the candidate's answer. No "interesting", "good", "I see", "thank you".
- NEVER use soft framing: no "Can you tell me", "I'd like to ask", "Let's talk about".
- NEVER explain the test or mention which part it is.
- Be direct: "Where do you live?" not "Could you describe where you live?"`;

  // ── Opening — Name request ──
  if (state.part === 1 && state.phase === "opening") {
    return `${base}

OUTPUT: Ask the candidate for their full name. Nothing else.
Example: "What is your full name?"`;
  }

  // ── Part 1: Interview Questions ──
  if (state.part === 1 && state.phase === "question") {
    const topicSet = getCurrentTopicSet(state);
    const questionHint = getQuestionHint(state);

    return `${base}

Topic: "${topicSet.theme}"
Guide question (rephrase, do not copy): "${questionHint}"

OUTPUT: One direct question about "${topicSet.theme}". Maximum 12 words.`;
  }

  // ── Part 2: follow-up ──
  if (state.part === 2 && state.phase === "follow_up") {
    const part2Response = (state.userResponses || []).slice(-1)[0] || "";
    const part2Summary = part2Response.length > 150 ? part2Response.substring(0, 150) + "..." : part2Response;

    return `${base}

The candidate spoke about: "${cueCard.topic}"
What they said: "${part2Summary}"

OUTPUT: One brief follow-up question about what the candidate said. Maximum 12 words.`;
  }

  // ── Part 3: discussion questions with DISCUSSION LADDER ──
  if (state.part === 3 && state.phase === "question_p3") {
    const analysis = analyzeResponseQuality(state);
    const themeLabel = cueCard.part3Theme || cueCard.topic.toLowerCase().replace("describe ", "");
    const tier = PART3_TIERS[state.part3Tier || 0] || "concrete";

    let tierHint;
    switch (tier) {
      case "concrete":
        tierHint = "Ask about observable facts or common behaviors.";
        break;
      case "comparative":
        tierHint = "Ask to compare across time, places, or groups.";
        break;
      case "analytical":
        tierHint = "Ask about causes, effects, or reasons.";
        break;
      case "evaluative":
        tierHint = "Ask to evaluate, judge, or predict.";
        break;
    }

    let adaptiveNote = "";
    if (analysis.level === "strong") {
      adaptiveNote = " Use nuanced phrasing.";
    } else if (analysis.level === "limited") {
      adaptiveNote = " Use simple phrasing.";
    }

    return `${base}

Theme: "${themeLabel}"
Tier: ${tier.toUpperCase()} — ${tierHint}${adaptiveNote}

OUTPUT: One discussion question about "${themeLabel}". Maximum 15 words.`;
  }

  return base;
}

// ---------------------------------------------------------------------------
// V2 Experimental: Enhanced examiner prompts with pushback
// ---------------------------------------------------------------------------

/**
 * V2: Build IELTS system prompt with pushback/challenge behavior for Part 3.
 * Every 2nd-3rd question challenges the candidate's previous position.
 */
function buildIeltsSystemPromptV2(state) {
  const cueCard = IELTS_CUE_CARDS[state.cueCardIndex % IELTS_CUE_CARDS.length];

  const base = `You generate IELTS Speaking examiner questions. Output ONLY the question — nothing else.

ABSOLUTE RULES:
- Output exactly ONE question. No commentary, no filler.
- Maximum 15 words.
- NEVER react to the candidate's answer. No "interesting", "good", "I see", "thank you".
- NEVER use soft framing: no "Can you tell me", "I'd like to ask", "Let's talk about".
- NEVER explain the test or mention which part it is.
- Be direct and professional.`;

  // For Part 1 and Part 2 — same as V1
  if (state.part === 1 && state.phase === "opening") {
    return `${base}\n\nOUTPUT: Ask the candidate for their full name. Nothing else.\nExample: "What is your full name?"`;
  }

  if (state.part === 1 && state.phase === "question") {
    const topicSet = getCurrentTopicSet(state);
    const questionHint = getQuestionHint(state);
    return `${base}\n\nTopic: "${topicSet.theme}"\nGuide question (rephrase, do not copy): "${questionHint}"\n\nOUTPUT: One direct question about "${topicSet.theme}". Maximum 12 words.`;
  }

  if (state.part === 2 && state.phase === "follow_up") {
    const part2Response = (state.userResponses || []).slice(-1)[0] || "";
    const part2Summary = part2Response.length > 150 ? part2Response.substring(0, 150) + "..." : part2Response;
    return `${base}\n\nThe candidate spoke about: "${cueCard.topic}"\nWhat they said: "${part2Summary}"\n\nOUTPUT: One brief follow-up question about what the candidate said. Maximum 12 words.`;
  }

  // ── V2 Part 3: Enhanced with pushback/challenge ──
  if (state.part === 3 && state.phase === "question_p3") {
    const analysis = analyzeResponseQuality(state);
    const themeLabel = cueCard.part3Theme || cueCard.topic.toLowerCase().replace("describe ", "");
    const tier = PART3_TIERS[state.part3Tier || 0] || "concrete";
    const questionIdx = state.questionIndex || 0;

    let tierHint;
    switch (tier) {
      case "concrete":
        tierHint = "Ask about observable facts or common behaviors.";
        break;
      case "comparative":
        tierHint = "Ask to compare across time, places, or groups.";
        break;
      case "analytical":
        tierHint = "Ask about causes, effects, or reasons.";
        break;
      case "evaluative":
        tierHint = "Ask to evaluate, judge, or predict.";
        break;
    }

    let adaptiveNote = "";
    if (analysis.level === "strong") {
      adaptiveNote = " Use nuanced phrasing.";
    } else if (analysis.level === "limited") {
      adaptiveNote = " Use simple phrasing.";
    }

    // V2: Pushback on every 2nd question (indices 1, 3)
    const shouldPushback = questionIdx % 2 === 1;
    let pushbackInstruction = "";

    if (shouldPushback) {
      const lastUserResponse = (state.userResponses || []).slice(-1)[0] || "";
      const lastSummary = lastUserResponse.length > 100 ? lastUserResponse.substring(0, 100) + "..." : lastUserResponse;

      pushbackInstruction = `
CHALLENGE MODE: The candidate just said: "${lastSummary}"
Challenge their position by asking a question from the opposite perspective.
Examples: "But don't you think...?", "What would you say to people who believe...?", "Could it also be argued that...?"
CRITICAL: Your output MUST be a question ending with "?". Never output a statement.
Do NOT agree with the candidate. Test their ability to defend their position.
Output ONE challenging question. Maximum 15 words. MUST end with "?".`;
    }

    return `${base}

Theme: "${themeLabel}"
Tier: ${tier.toUpperCase()} — ${tierHint}${adaptiveNote}
${pushbackInstruction}
OUTPUT: One ${shouldPushback ? "challenging" : "discussion"} question about "${themeLabel}". Maximum 15 words.`;
  }

  return base;
}

// ---------------------------------------------------------------------------
// V2: Enhanced scoring prompt with Vietnamese L1 detection
// ---------------------------------------------------------------------------

const V2_SCORING_ADDENDUM = `

VIETNAMESE L1 PRONUNCIATION PATTERNS (CRITICAL FOR THIS LEARNER):
Vietnamese speakers have specific, predictable pronunciation patterns that IELTS examiners recognize.
You MUST check for and report on these patterns in your criteriaFeedback.pronunciation:

1. FINAL CONSONANT DELETION: Vietnamese has no final consonant clusters. Speakers commonly drop
   word-final /t/, /d/, /s/, /z/, /k/, /θ/. Examples: "walked" → "walk", "friends" → "frien",
   "months" → "mon". If you see simplified word endings in the transcript, mention this.

2. FLAT INTONATION: Vietnamese is a tonal language but English uses pitch for emphasis/structure.
   Vietnamese speakers often produce flat, monotone English. Note if responses lack natural stress
   patterns or sound monotone.

3. FILLER PATTERNS: Vietnamese speakers may use extended pauses or Vietnamese-influenced fillers.
   Bridging phrases ("Let me think", "What I mean is") maintain fluency scores during thinking time.

In criteriaFeedback.pronunciation, ALWAYS mention if you detect Vietnamese L1 interference patterns.
Be specific: name the pattern, give examples from the transcript, explain impact on the score.

BAND RANGE OUTPUT:
For each criterion, also include a "bandRange" field in criteriaFeedback as a string like "5.5-6.0"
to indicate the estimated IELTS band range (not just a single number).`;

// ---------------------------------------------------------------------------
// Part-tagging for scorer — provides structural context
// ---------------------------------------------------------------------------

/**
 * Tag conversation turns with part labels so the scorer knows which part
 * each response belongs to. This enables weighted scoring (Part 2/3 > Part 1).
 */
function tagConversationParts(filteredTurns, meta) {
  // Reconstruct part boundaries from transition history
  const transitions = meta.transitionHistory || [];
  const partBoundaries = []; // { turnIndex, part, phase }

  // Parse transitions to find where each part starts
  let currentPart = 1;
  let turnCounter = 0;

  // Simple heuristic: count user turns to estimate part boundaries
  const userTurns = filteredTurns.filter(t => t.role === "user");
  const openingTurns = 1; // opening (name) only — no id_check
  const part1Turns = IELTS_PART1_TOTAL_QUESTIONS;
  const part2Turns = 1; // long turn
  // Remaining = Part 3

  return filteredTurns.map((t, i) => {
    if (t.role !== "user") {
      return { role: t.role, content: t.content };
    }

    // Count this user turn's position
    const userIdx = filteredTurns.slice(0, i + 1).filter(x => x.role === "user").length - 1;

    let partLabel;
    if (userIdx < openingTurns) {
      partLabel = "[Part 1 — Opening]";
    } else if (userIdx < openingTurns + part1Turns) {
      const qNum = userIdx - openingTurns + 1;
      partLabel = `[Part 1, Q${qNum}]`;
    } else if (userIdx === openingTurns + part1Turns) {
      partLabel = "[Part 2 — Long Turn]";
    } else if (userIdx === openingTurns + part1Turns + 1) {
      partLabel = "[Part 2 — Follow-up]";
    } else {
      const p3Idx = userIdx - openingTurns - part1Turns - 2;
      partLabel = `[Part 3, Q${p3Idx + 1}]`;
    }

    return { role: t.role, content: `${partLabel} ${t.content}` };
  });
}

// ---------------------------------------------------------------------------
// Scenario catalogue
// ---------------------------------------------------------------------------

async function listScenarios(category) {
  return scenarioRepository.findAllScenarios(category);
}

async function getScenario(id) {
  const scenario = await scenarioRepository.findScenarioById(id);
  if (!scenario) {
    const err = new Error("Scenario not found");
    err.status = 404;
    throw err;
  }
  return scenario;
}

// ---------------------------------------------------------------------------
// Session lifecycle
// ---------------------------------------------------------------------------

async function startSession(scenarioId, userId, options = {}) {
  const scenario = await scenarioRepository.findScenarioById(scenarioId);
  if (!scenario) {
    const err = new Error("Scenario not found");
    err.status = 404;
    throw err;
  }

  // Check daily speaking limit
  try {
    const { checkSpeakingLimit } = require("./limitService");
    const limit = await checkSpeakingLimit(userId);
    if (!limit.allowed) {
      const err = new Error("Daily speaking limit reached. Upgrade to Pro for unlimited sessions.");
      err.status = 403;
      err.code = "SPEAKING_LIMIT_REACHED";
      err.limitData = { used: limit.used, limit: limit.limit };
      throw err;
    }
  } catch (e) {
    if (e.code === "SPEAKING_LIMIT_REACHED") throw e;
    // If limitService fails, don't block the session
  }

  await scenarioRepository.abandonActiveSession(userId);
  const session = await scenarioRepository.createSession(scenarioId, userId);

  const isIelts = scenario.category === "exam";
  let openingContent;
  let cueCardIndex = -1;
  let examinerPersonaOut;

  if (isIelts) {
    // V2: Allow cueCardIndex override for retry-same-topic
    const isRetry = options.cueCardIndex != null && options.cueCardIndex >= 0 && options.cueCardIndex < IELTS_CUE_CARDS.length;
    cueCardIndex = isRetry
      ? options.cueCardIndex
      : Math.floor(Math.random() * IELTS_CUE_CARDS.length);
    // V2: On retry, align Part 1 topics with the cue card theme
    const initialState = createInitialIeltsState(cueCardIndex, isRetry);

    // Pick examiner persona + compute local greeting. Backend is the single
    // source of truth for both — frontend only renders.
    const persona = pickPersona();
    const timezone = normalizeTimezone(options.timezone);
    const greeting = computeGreeting(new Date(), timezone);

    initialState.examinerPersona = { name: persona.name, voice: persona.voice };
    initialState.greeting = greeting;
    initialState.timezone = timezone;
    examinerPersonaOut = initialState.examinerPersona;

    // Persist state to DB
    await scenarioRepository.updateSessionMeta(session.id, initialState);

    // Opening is built from a hardcoded template — no LLM call. Keeps the
    // examiner's first utterance fully deterministic (Zero Reaction safe).
    openingContent = buildOpeningMessage(persona, greeting);

    console.log(`[ielts] Session started: ${session.id} | cueCard: ${cueCardIndex} | persona: ${persona.name}/${persona.voice} | tz: ${timezone} | greeting: ${greeting}`);
  } else {
    openingContent = scenario.opening_message;
  }

  const openingTurn = await scenarioRepository.insertTurn(
    session.id, 0, "assistant", openingContent
  );

  // Return cue card so frontend can display it during Part 2
  const cueCard = isIelts
    ? IELTS_CUE_CARDS[(await scenarioRepository.getSessionMeta(session.id))?.cueCardIndex ?? 0]
    : null;

  return {
    sessionId: session.id,
    title: session.title,
    emoji: session.emoji,
    category: session.category,
    cueCard: cueCard || undefined,
    cueCardIndex: isIelts ? cueCardIndex : undefined,
    examinerPersona: examinerPersonaOut,
    turns: [{
      turnIndex: openingTurn.turn_index,
      role: openingTurn.role,
      content: openingTurn.content,
      createdAt: openingTurn.created_at,
    }],
  };
}

async function submitTurn(sessionId, userId, content, speechMetrics = null, options = {}) {
  const session = await scenarioRepository.findSessionById(sessionId);
  if (!session) {
    const err = new Error("Session not found");
    err.status = 404;
    throw err;
  }
  if (session.user_id !== userId) {
    const err = new Error("Not authorized to access this session");
    err.status = 403;
    throw err;
  }
  if (session.status !== "active") {
    const err = new Error("Session is no longer active");
    err.status = 400;
    throw err;
  }

  const existingTurns = await scenarioRepository.findSessionTurns(sessionId);
  const nextIndex = existingTurns.length;

  // Save user turn
  const userTurn = await scenarioRepository.insertTurn(sessionId, nextIndex, "user", content);

  // Build conversation history for AI
  const conversationHistory = existingTurns.map(t => ({ role: t.role, content: t.content }));
  conversationHistory.push({ role: "user", content });

  const isIelts = session.category === "exam";
  let aiContent;
  let ieltsState = null;

  if (isIelts) {
    // ── Read current state from DB ──
    const currentState = await scenarioRepository.getSessionMeta(sessionId);
    if (!currentState || !currentState.part) {
      console.error(`[ielts] FATAL: No state found for session ${sessionId}`);
      const err = new Error("IELTS session state corrupted");
      err.status = 500;
      throw err;
    }

    // ── Track user response quality (skip placeholders) ──
    const isPlaceholder = content.startsWith("[") && content.endsWith("]");
    if (!isPlaceholder) {
      const wordCount = content.trim().split(/\s+/).filter(Boolean).length;
      currentState.userWordCounts = [...(currentState.userWordCounts || []), wordCount];
      currentState.userResponses = [...(currentState.userResponses || []), content];
      currentState.userResponseCount = (currentState.userResponseCount || 0) + 1;

      // ── Audio Intelligence: Store speechMetrics per turn ──
      if (speechMetrics) {
        currentState.turnSpeechMetrics = [
          ...(currentState.turnSpeechMetrics || []),
          { turnIndex: nextIndex, ...speechMetrics },
        ];
        console.log(`[speech] session=${sessionId} | wpm=${speechMetrics.wordsPerMinute} | pauses=${speechMetrics.pauseCount} | ratio=${speechMetrics.speakingRatio}`);
      }

      // ── Track Part 3 previous word count for de-escalation ──
      if (currentState.part === 3 && currentState.phase === "question_p3") {
        currentState.part3PrevWordCount = wordCount;
      }
    }

    const fromState = `part${currentState.part}:${currentState.phase}:${currentState.questionIndex}`;

    // ── EXPLICIT transition — advance to next state ──
    const nextState = advanceIeltsState(currentState);
    // Carry forward metadata
    nextState.userWordCounts = currentState.userWordCounts;
    nextState.userResponses = currentState.userResponses;
    nextState.userResponseCount = currentState.userResponseCount;
    nextState.part3PrevWordCount = currentState.part3PrevWordCount || 0;
    nextState.turnSpeechMetrics = currentState.turnSpeechMetrics || [];

    // Part 2 notepad: persist whatever the candidate jotted during the 60s prep.
    // Only accept notes on the prep→speak transition — any other time it's a
    // stale client or a bug, and silently ignoring keeps the API forgiving.
    // Notes never reach the scoring prompt; they are pure UX aid.
    if (typeof options.part2Notes === "string" && currentState.part === 2 && currentState.phase === "cue_card") {
      nextState.part2Notes = options.part2Notes;
    } else if (currentState.part2Notes !== undefined) {
      nextState.part2Notes = currentState.part2Notes;
    }
    ieltsState = nextState;

    const toState = `part${nextState.part}:${nextState.phase}:${nextState.questionIndex}`;
    console.log(`[ielts] session=${sessionId} | ${fromState} → ${toState}`);

    // ── OUTPUT CONTRACT: Generate response based on state ──
    // Transitions are HARDCODED. Questions go through LLM + validation.
    const isExperimentalTransition = options.experimental === true;
    const transitions = isExperimentalTransition ? FIXED_TRANSITIONS_V2 : FIXED_TRANSITIONS;
    if (nextState.phase === "complete") {
      aiContent = transitions.closing;
    } else if (nextState.phase === "part1_transition") {
      aiContent = transitions.part1;
    } else if (nextState.phase === "transition_to_part2") {
      aiContent = transitions.part2;
    } else if (nextState.phase === "transition_to_part3") {
      aiContent = transitions.part3;
    } else if (nextState.phase === "cue_card") {
      const cueCard = IELTS_CUE_CARDS[nextState.cueCardIndex % IELTS_CUE_CARDS.length];
      aiContent = `Your topic is: "${cueCard.topic}".`;
    } else if (nextState.phase === "long_turn") {
      aiContent = transitions.prepStart;
    } else {
      // LLM generates a question — then we sanitize it
      // V2: Use enhanced prompt with pushback if experimental mode
      const isExperimental = options.experimental === true;
      const systemPrompt = isExperimental
        ? buildIeltsSystemPromptV2(nextState)
        : buildIeltsSystemPrompt(nextState);
      const rawResponse = await ai.generateResponse(systemPrompt, conversationHistory, { category: "exam" });
      aiContent = sanitizeExaminerOutput(rawResponse);
      console.log(`[ielts${isExperimental ? "-v2" : ""}] raw="${rawResponse.slice(0, 80)}" → sanitized="${aiContent}"`);
    }

    // ── Persist the new state to DB ──
    await scenarioRepository.updateSessionMeta(sessionId, nextState);
  } else {
    console.log(`[ai] session: ${sessionId} | category: ${session.category} | turns: ${conversationHistory.length}`);
    aiContent = await ai.generateResponse(
      session.system_prompt,
      conversationHistory,
      { category: session.category }
    );
  }

  // Save AI turn
  const aiTurn = await scenarioRepository.insertTurn(sessionId, nextIndex + 1, "assistant", aiContent);

  return {
    userTurn: {
      turnIndex: userTurn.turn_index,
      role: userTurn.role,
      content: userTurn.content,
      createdAt: userTurn.created_at,
    },
    aiTurn: {
      turnIndex: aiTurn.turn_index,
      role: aiTurn.role,
      content: aiTurn.content,
      createdAt: aiTurn.created_at,
    },
    ieltsState,
  };
}

// ---------------------------------------------------------------------------
// Placeholder detection — filter internal signals from scoring
// ---------------------------------------------------------------------------

const PLACEHOLDER_PATTERNS = [
  /^\[READY FOR PART [123]\]$/,
  /^\[PREP(ARATION)? (TIME )?COMPLETE/,
  /^\[Speaking completed\]$/,
  /^\[PREPARATION COMPLETE\]$/,
];

function isPlaceholderTurn(content) {
  return PLACEHOLDER_PATTERNS.some(p => p.test(content.trim()));
}

/**
 * Filter conversation history: remove placeholder turns that are internal
 * state-machine signals, not real candidate speech.
 */
function filterPlaceholders(turns) {
  return turns.filter(t => {
    if (t.role === "user" && isPlaceholderTurn(t.content)) return false;
    return true;
  });
}

// ---------------------------------------------------------------------------
// Hybrid scoring — strict IELTS-realistic
// ---------------------------------------------------------------------------

function computeHybridPenalties(turns) {
  // Only score real user turns (excluding placeholders)
  const userTurns = turns.filter(t => t.role === "user" && !isPlaceholderTurn(t.content));
  const totalWords = userTurns.reduce(
    (sum, t) => sum + t.content.trim().split(/\s+/).filter(Boolean).length, 0
  );
  const avgWords = userTurns.length > 0 ? totalWords / userTurns.length : 0;

  let penalty = 1.0;
  let floorScore = 0;

  if (avgWords < 3) {
    penalty = 0.35;
    floorScore = 0;
  } else if (avgWords < 6) {
    penalty = 0.55;
    floorScore = 0;
  } else if (avgWords < 10) {
    penalty = 0.75;
    floorScore = 20;
  } else if (avgWords < 20) {
    penalty = 0.90;
    floorScore = 30;
  }

  const copOuts = userTurns.filter(t => {
    const lower = t.content.toLowerCase();
    return lower.includes("i don't know") ||
           lower.includes("i have no idea") ||
           lower.includes("i can't answer") ||
           lower.includes("no comment") ||
           (lower.includes("pass") && t.content.trim().length < 10);
  });

  if (copOuts.length > userTurns.length * 0.5) {
    penalty = Math.min(penalty, 0.3);
  } else if (copOuts.length > 0) {
    penalty = Math.min(penalty, penalty * 0.7);
  }

  return { penalty, floorScore, avgWords, totalWords };
}

/**
 * Convert a 0-100 score to an IELTS band (1.0–9.0 in 0.5 increments).
 */
function toBandScore(score100) {
  // Map: 0→1, 20→3, 40→4.5, 60→6, 75→7, 85→7.5, 95→8.5, 100→9
  if (score100 >= 95) return 9.0;
  if (score100 >= 90) return 8.5;
  if (score100 >= 85) return 8.0;
  if (score100 >= 80) return 7.5;
  if (score100 >= 75) return 7.0;
  if (score100 >= 70) return 6.5;
  if (score100 >= 60) return 6.0;
  if (score100 >= 50) return 5.5;
  if (score100 >= 40) return 5.0;
  if (score100 >= 30) return 4.5;
  if (score100 >= 20) return 4.0;
  if (score100 >= 10) return 3.0;
  return 2.0;
}

async function endSession(sessionId, userId, durationMs, options = {}) {
  const session = await scenarioRepository.findSessionById(sessionId);
  if (!session) {
    const err = new Error("Session not found");
    err.status = 404;
    throw err;
  }
  if (session.user_id !== userId) {
    const err = new Error("Not authorized to access this session");
    err.status = 403;
    throw err;
  }
  if (session.status !== "active") {
    const err = new Error("Session is no longer active");
    err.status = 400;
    throw err;
  }

  const turns = await scenarioRepository.findSessionTurns(sessionId);

  // Filter placeholder turns before scoring (keep in DB for audit trail)
  const filteredTurns = filterPlaceholders(turns);
  const conversationHistory = filteredTurns.map(t => ({ role: t.role, content: t.content }));

  // Log transition history for auditability
  const meta = await scenarioRepository.getSessionMeta(sessionId);
  if (meta?.transitionHistory) {
    console.log(`[ielts] Session ${sessionId} transition history:`);
    meta.transitionHistory.forEach(t => console.log(`  ${t}`));
  }

  const isIelts = session.category === "exam";
  console.log(`[ai] scoring session: ${sessionId} | turns: ${conversationHistory.length} (filtered from ${turns.length}) | isIelts: ${isIelts}`);

  // ── Audio Intelligence: Analyze speech flow across all user turns ──
  const realUserTurnsForAnalysis = filteredTurns
    .filter(t => t.role === "user" && !isPlaceholderTurn(t.content));

  const turnSpeechMetricsMap = new Map();
  if (meta?.turnSpeechMetrics) {
    for (const m of meta.turnSpeechMetrics) {
      turnSpeechMetricsMap.set(m.turnIndex, m);
    }
  }

  const turnsForAggregation = realUserTurnsForAnalysis.map(t => ({
    text: t.content,
    speechMetrics: turnSpeechMetricsMap.get(t.turn_index) || null,
  }));

  const speechFlow = aggregateSpeechFlow(turnsForAggregation);
  console.log(`[speech] session=${sessionId} | fillers=${speechFlow.totalFillerCount} | corrections=${speechFlow.totalSelfCorrections} | hesitation=${speechFlow.hesitationLevel} | fluencyEst=${speechFlow.fluencyEstimate}${speechFlow.avgWordsPerMinute ? ` | wpm=${speechFlow.avgWordsPerMinute}` : ""}`);

  // ── Examiner Brain: Part-tag conversation for scorer context ──
  let scoringHistory = conversationHistory;
  if (isIelts && meta) {
    scoringHistory = tagConversationParts(filteredTurns, meta);
  }

  const isExperimental = options.experimental === true;
  const aiScores = await ai.scoreConversation(session.system_prompt, scoringHistory, {
    isIelts,
    speechFlow, // Pass speech analysis to scoring prompt
    experimentalAddendum: isExperimental ? V2_SCORING_ADDENDUM : null,
  });
  const { penalty, floorScore, avgWords, totalWords } = computeHybridPenalties(turns);

  // ── Audio Intelligence: Speech-aware fluency modifier ──
  // If speech analysis detected high hesitation, apply additional fluency penalty
  let speechFluencyModifier = 1.0;
  if (speechFlow.hesitationLevel === "high") {
    speechFluencyModifier = 0.85; // 15% penalty for high hesitation
  } else if (speechFlow.hesitationLevel === "medium") {
    speechFluencyModifier = 0.93; // 7% penalty for medium hesitation
  }

  const adjustedFluency = Math.max(floorScore, Math.round(aiScores.fluency * penalty * speechFluencyModifier));
  const adjustedVocab = Math.max(floorScore, Math.round(aiScores.vocabulary * penalty));
  const adjustedGrammar = Math.max(floorScore, Math.round(aiScores.grammar * penalty));
  const adjustedPronunciation = Math.max(floorScore, Math.round((aiScores.pronunciation || aiScores.fluency) * penalty));
  const adjustedOverall = Math.round((adjustedFluency + adjustedVocab + adjustedGrammar + adjustedPronunciation) / 4);

  console.log(`[scoring] AI: ${aiScores.overallScore} | penalty: ${penalty} | speechMod: ${speechFluencyModifier} | avgWords: ${avgWords.toFixed(1)} | adjusted: ${adjustedOverall}`);

  let coachFeedback = aiScores.coachFeedback;
  if (adjustedOverall < 30) {
    coachFeedback = "You need to provide longer, more detailed answers. In IELTS Speaking, one-word or very short responses will significantly lower your score. Try to speak in full sentences and expand on your ideas.";
  } else if (adjustedOverall < 50) {
    coachFeedback = "Your answers need more development. Try to give reasons and examples when you answer. Aim for at least 2-3 sentences per response in Part 1, and much longer responses in Parts 2 and 3.";
  }

  // Extract real user turns (excluding placeholders)
  const realUserTurns = turns.filter(t => t.role === "user" && !isPlaceholderTurn(t.content));
  const turnCount = realUserTurns.length;
  const wordCount = totalWords;

  // Band score conversion for IELTS
  const bandScore = isIelts ? toBandScore(adjustedOverall) : null;

  // Notable vocabulary + enhanced feedback from AI scoring
  const notableVocabulary = aiScores.notableVocabulary || [];
  const improvementVocabulary = aiScores.improvementVocabulary || [];
  const criteriaFeedback = aiScores.criteriaFeedback || null;
  const feedbackCards = aiScores.feedback_cards || [];
  const sampleBand8Answer = aiScores.sample_band8_answer || null;
  const sessionStrengths = aiScores.session_strengths || [];
  const top3Priorities = aiScores.top_3_priorities || [];

  await scenarioRepository.completeSession(sessionId, {
    overallScore: adjustedOverall,
    fluencyScore: adjustedFluency,
    vocabularyScore: adjustedVocab,
    grammarScore: adjustedGrammar,
    coachFeedback,
    turnCount,
    wordCount,
    durationMs: durationMs || 0,
  });

  // ── Gamification: Award XP + update streak on scenario completion ──
  // xp_ledger has no lesson_id column — we use the sessionId as ref_id.
  // learning_events is NOT written here (that table requires lesson_id).
  // updateStreak is idempotent for same-day calls (no double-counting).
  try {
    const xpReward = isIelts ? XP_REWARD_IELTS : XP_REWARD_SCENARIO;
    const reason   = isIelts ? "ielts_session_complete" : "scenario_session_complete";
    await awardXp(userId, xpReward, reason, sessionId);
  } catch (err) {
    // Non-fatal: XP award failure should not break session scoring
    console.error(`[scenario] XP award failed for user ${userId}:`, err.message);
  }

  try {
    await updateStreak(userId);
  } catch (err) {
    // Non-fatal: streak update failure should not break session scoring
    console.error(`[scenario] streak update failed for user ${userId}:`, err.message);
  }

  // ── Audio Intelligence: Build speech insights for frontend ──
  const speechInsights = {
    hesitationLevel: speechFlow.hesitationLevel,
    fluencyEstimate: speechFlow.fluencyEstimate,
    fillerSummary: speechFlow.fillerSummary,
    totalFillerCount: speechFlow.totalFillerCount,
    totalSelfCorrections: speechFlow.totalSelfCorrections,
    avgWordsPerMinute: speechFlow.avgWordsPerMinute,
    avgSpeakingRatio: speechFlow.avgSpeakingRatio,
  };

  // Fire-and-forget: update user's estimated band (if band score exists)
  if (bandScore != null && bandScore > 0) {
    try {
      const { updateUserBand } = require("../repositories/userRepository");
      updateUserBand(userId, bandScore, "speaking", sessionId).catch(() => {});
    } catch { /* module load safety */ }
  }

  // Fire-and-forget: update study room activity tracking
  try {
    const { onUserCompletedActivity } = require("./studyRoomService");
    onUserCompletedActivity(userId, "speaking_sessions", 1).catch(() => {});
  } catch { /* module load safety */ }

  // Fire-and-forget: check speaking achievements (log errors, don't swallow)
  try {
    const { checkSpeakingBadges } = require("./badgeService");
    const countRow = await require("../config/db").query(
      `SELECT COUNT(*)::int AS c FROM scenario_sessions WHERE user_id = $1 AND status = 'completed'`, [userId]
    );
    checkSpeakingBadges(userId, countRow.rows[0]?.c ?? 0, bandScore).catch((err) => {
      console.error(`[scenario] badge check failed for user ${userId}:`, err.message);
    });
  } catch (err) {
    console.error(`[scenario] badge module load failed:`, err.message);
  }

  return {
    overallScore: adjustedOverall,
    fluency: adjustedFluency,
    vocabulary: adjustedVocab,
    grammar: adjustedGrammar,
    pronunciation: adjustedPronunciation,
    bandScore,
    criteriaFeedback,
    coachFeedback,
    turnFeedback: aiScores.turnFeedback,
    notableVocabulary,
    improvementVocabulary,
    speechInsights,
    feedbackCards,
    sampleBand8Answer,
    sessionStrengths,
    top3Priorities,
    turnCount,
    wordCount,
    durationMs: durationMs || 0,
  };
}

// ---------------------------------------------------------------------------
// Session queries
// ---------------------------------------------------------------------------

async function getSessionDetail(sessionId, userId) {
  const session = await scenarioRepository.findSessionById(sessionId);
  if (!session) {
    const err = new Error("Session not found");
    err.status = 404;
    throw err;
  }
  if (session.user_id !== userId) {
    const err = new Error("Not authorized to access this session");
    err.status = 403;
    throw err;
  }

  const turns = await scenarioRepository.findSessionTurns(sessionId);

  return {
    sessionId: session.id,
    scenarioId: session.scenario_id,
    title: session.title,
    emoji: session.emoji,
    category: session.category,
    status: session.status,
    overallScore: session.overall_score,
    fluencyScore: session.fluency_score,
    vocabularyScore: session.vocabulary_score,
    grammarScore: session.grammar_score,
    coachFeedback: session.coach_feedback,
    turnCount: session.turn_count,
    wordCount: session.word_count,
    durationMs: session.duration_ms,
    startedAt: session.started_at,
    completedAt: session.completed_at,
    turns: turns.map(t => ({
      turnIndex: t.turn_index,
      role: t.role,
      content: t.content,
      createdAt: t.created_at,
    })),
  };
}

async function getUserSessions(userId) {
  return scenarioRepository.findSessionsByUser(userId);
}

module.exports = {
  listScenarios,
  getScenario,
  startSession,
  submitTurn,
  endSession,
  getSessionDetail,
  getUserSessions,
};
